#!/bin/bash

# Generic Slidev PDF Builder
# This script automatically finds and builds all .md files to PDF format

set -e  # Exit on any error

echo "📄 Generic Slidev PDF Builder"
echo "============================="

# Create output directory
OUTPUT_DIR="pdf-exports"
mkdir -p "$OUTPUT_DIR"

# Check if Slidev is installed
if ! command -v slidev &> /dev/null; then
    echo "❌ Slidev is not installed. Installing..."
    npm install -g @slidev/cli
    echo "✅ Slidev installed successfully"
fi

# Automatically find all .md files in current directory
PRESENTATIONS=($(find . -maxdepth 1 -name "*.md" -type f | sort))

# Function to build a single presentation
build_presentation() {
    local file=$1
    local basename=$(basename "$file" .md)
    local output="$OUTPUT_DIR/$basename.pdf"
    
    echo ""
    echo "📄 Building $file..."
    
    if [ ! -f "$file" ]; then
        echo "⚠️  Warning: $file not found, skipping..."
        return 1
    fi
    
    # Check if file is a Slidev presentation (contains frontmatter)
    if ! head -n 10 "$file" | grep -q "^---$"; then
        echo "⚠️  Warning: $file doesn't appear to be a Slidev presentation (no frontmatter), skipping..."
        return 1
    fi
    
    # Skip if PDF already exists and is up-to-date (unless forced)
    if [ -f "$output" ] && [ "$FORCE" != true ]; then
        if [ "$output" -nt "$file" ]; then
            echo "⏭️  Skipping $file (up-to-date PDF already exists)"
            return 0
        fi
    fi
    
    # Build PDF with Slidev using export command
    slidev export "$file" --format pdf --output "$output"
    
    # Check if PDF was created successfully
    if [ -f "$output" ]; then
        echo "✅ PDF file created: $basename.pdf"
    else
        echo "❌ Failed to create PDF: $basename.pdf"
        return 1
    fi
    
    if [ $? -eq 0 ]; then
        echo "✅ Successfully built: $basename.pdf"
    else
        echo "❌ Failed to build: $file"
        return 1
    fi
}

# Function to build all presentations
build_all() {
    echo "🚀 Starting PDF build process..."
    echo "Output directory: $OUTPUT_DIR"
    echo ""
    
    local success_count=0
    local total_count=${#PRESENTATIONS[@]}
    
    for presentation in "${PRESENTATIONS[@]}"; do
        if build_presentation "$presentation"; then
            ((success_count++))
        fi
    done
    
    echo ""
    echo "📊 Build Summary:"
    echo "================="
    echo "✅ Successfully built: $success_count/$total_count presentations"
    echo "📁 Output directory: $OUTPUT_DIR/"
    
    if [ $success_count -eq $total_count ]; then
        echo "🎉 All presentations built successfully!"
    else
        echo "⚠️  Some presentations failed to build. Check the output above."
        exit 1
    fi
}

# Function to create a combined PDF (optional)
create_combined_pdf() {
    echo ""
    echo "📚 Creating combined PDF..."
    
    if command -v pdftk &> /dev/null; then
        # Use pdftk to combine PDFs
        pdftk "$OUTPUT_DIR"/*.pdf cat output "$OUTPUT_DIR/Combined-Presentations.pdf"
        echo "✅ Combined PDF created: Combined-Presentations.pdf"
    elif command -v gs &> /dev/null; then
        # Use Ghostscript to combine PDFs
        gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile="$OUTPUT_DIR/Combined-Presentations.pdf" "$OUTPUT_DIR"/*.pdf
        echo "✅ Combined PDF created: Combined-Presentations.pdf"
    else
        echo "⚠️  Neither pdftk nor Ghostscript found. Skipping combined PDF creation."
        echo "   Install pdftk or Ghostscript to create a combined PDF."
    fi
}

# Function to create an index file
create_index() {
    echo ""
    echo "📋 Creating index file..."
    
    cat > "$OUTPUT_DIR/README.md" << EOF
# Slidev PDF Exports

This directory contains PDF exports of all Slidev presentations found in the current directory.

## Available Presentations

EOF

    for presentation in "${PRESENTATIONS[@]}"; do
        local basename=$(basename "$presentation" .md)
        if [ -f "$OUTPUT_DIR/$basename.pdf" ]; then
            echo "- **$basename.pdf** - $(echo $basename | sed 's/-/ /g' | sed 's/\b\w/\U&/g')" >> "$OUTPUT_DIR/README.md"
        fi
    done
    
    cat >> "$OUTPUT_DIR/README.md" << EOF

## Build Information

- **Build Date:** $(date)
- **Slidev Version:** $(slidev --version 2>/dev/null || echo "Unknown")
- **Total Files:** $(ls -1 "$OUTPUT_DIR"/*.pdf 2>/dev/null | wc -l)

## Usage

1. Open any PDF file to view the presentation
2. Use the combined PDF for a complete course overview
3. All presentations are optimized for both screen and print viewing

## Notes

- PDFs are generated with high quality settings
- All animations are converted to static slides
- Code blocks are syntax highlighted
- Mathematical formulas are properly rendered

---
*Generated by build-pdfs.sh script*
EOF

    echo "✅ Index file created: README.md"
}

# Function to show help
show_help() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -h, --help     Show this help message"
    echo "  -a, --all      Build all presentations (default)"
    echo "  -c, --combine  Also create a combined PDF"
    echo "  -i, --index    Also create an index file"
    echo "  -f, --file     Build specific file (e.g., -f presentation.md)"
    echo "      --force    Rebuild even if output PDF is up-to-date"
    echo ""
    echo "Examples:"
    echo "  $0                    # Build all .md files in current directory"
    echo "  $0 -c -i             # Build all + combine + index"
    echo "  $0 -f presentation.md # Build only specific file"
}

# Parse command line arguments
COMBINE=false
INDEX=false
SPECIFIC_FILE=""
FORCE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -a|--all)
            # Default behavior
            shift
            ;;
        -c|--combine)
            COMBINE=true
            shift
            ;;
        -i|--index)
            INDEX=true
            shift
            ;;
        -f|--file)
            SPECIFIC_FILE="$2"
            shift 2
            ;;
        --force)
            FORCE=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Main execution
if [ -n "$SPECIFIC_FILE" ]; then
    echo "🎯 Building specific file: $SPECIFIC_FILE"
    build_presentation "$SPECIFIC_FILE"
else
    build_all
fi

# Optional operations
if [ "$COMBINE" = true ]; then
    create_combined_pdf
fi

if [ "$INDEX" = true ]; then
    create_index
fi

echo ""
echo "🎉 Build process completed!"
echo "📁 Check the '$OUTPUT_DIR' directory for your PDF files."
